// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"database/sql"
)

type Cidade struct {
	ID        string
	Descricao string
	EstadoID  string
	CodIbge   string
}

type Cliente struct {
	ID          string
	CodigoMc    int64
	EmpresaID   string
	Nome        string
	Cep         sql.NullString
	CidadeID    sql.NullString
	Endereco    sql.NullString
	Numero      sql.NullString
	Complemento sql.NullString
}

type Empresa struct {
	ID            string
	Descricao     string
	Cnpj          sql.NullString
	ChaveRegistro sql.NullString
}

type Estado struct {
	ID        string
	Descricao string
	Uf        string
	CodIbge   int32
}

type ItensVenda struct {
	ID         string
	EmpresaID  string
	VendaID    string
	ProdutoID  string
	Quantidade float64
	Valor      float64
	Total      float64
}

type MaquininhasPo struct {
	ID             string
	IDEmpresa      string
	Administradora sql.NullString
	Cnpj           sql.NullString
}

type Pagamento struct {
	ID           string
	EmpresaID    string
	Descricao    string
	TpPagamento  string
	IndPagamento string
	PosExclusivo bool
	IDPos        sql.NullString
}

type PagamentosVenda struct {
	ID          string
	VendaID     string
	PagamentoID string
	Valor       float64
	Vencimento  sql.NullTime
	Status      bool
}

type Produto struct {
	ID        string
	EmpresaID string
	CodigoMc  string
	Descricao string
	CodBarras sql.NullString
	Ncm       sql.NullString
	Cest      sql.NullString
	Cbenef    sql.NullString
	Preco     float64
}

type Venda struct {
	ID        string
	EmpresaID string
	ClienteID string
	VendaMc   string
	Total     float64
	Data      sql.NullTime
	Status    bool
}
